<a href="https://colab.research.google.com/github/dasalgadob/pythonAlgoritmhs/blob/master/numpy/Numpy_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.arange(15)

In [3]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [0]:
b= a.reshape(5,3)

#### Basic funcions

In [14]:
print(b.shape)
print(type(a))
      

(5, 3)
<class 'numpy.ndarray'>


In [9]:
b.ndim #number of axes

2

In [10]:
a.ndim

1

In [11]:
a.dtype.name

'int64'

In [13]:
b.size #Total number of elements

15

#### Arrays

In [17]:
c =np.array([1,2,3,4.5])
print(c)

[1.  2.  3.  4.5]


In [19]:
print(c.dtype.name)

float64


In [20]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [0]:
d = np.pad(b, ((1,1), (1,1)), 'constant', constant_values = (0,0))

In [26]:
d

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  0],
       [ 0,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  0],
       [ 0,  9, 10, 11,  0],
       [ 0, 12, 13, 14,  0],
       [ 0,  0,  0,  0,  0]])

In [0]:
np.random.seed(1)
a_slice_prev = np.random.randn(4, 4, 3)
W = np.random.randn(4, 4, 3)
b = np.random.randn(1, 1, 1)


In [28]:
print(a_slice_prev)

[[[ 1.62434536 -0.61175641 -0.52817175]
  [-1.07296862  0.86540763 -2.3015387 ]
  [ 1.74481176 -0.7612069   0.3190391 ]
  [-0.24937038  1.46210794 -2.06014071]]

 [[-0.3224172  -0.38405435  1.13376944]
  [-1.09989127 -0.17242821 -0.87785842]
  [ 0.04221375  0.58281521 -1.10061918]
  [ 1.14472371  0.90159072  0.50249434]]

 [[ 0.90085595 -0.68372786 -0.12289023]
  [-0.93576943 -0.26788808  0.53035547]
  [-0.69166075 -0.39675353 -0.6871727 ]
  [-0.84520564 -0.67124613 -0.0126646 ]]

 [[-1.11731035  0.2344157   1.65980218]
  [ 0.74204416 -0.19183555 -0.88762896]
  [-0.74715829  1.6924546   0.05080775]
  [-0.63699565  0.19091548  2.10025514]]]


In [29]:
print(W)

[[[ 0.12015895  0.61720311  0.30017032]
  [-0.35224985 -1.1425182  -0.34934272]
  [-0.20889423  0.58662319  0.83898341]
  [ 0.93110208  0.28558733  0.88514116]]

 [[-0.75439794  1.25286816  0.51292982]
  [-0.29809284  0.48851815 -0.07557171]
  [ 1.13162939  1.51981682  2.18557541]
  [-1.39649634 -1.44411381 -0.50446586]]

 [[ 0.16003707  0.87616892  0.31563495]
  [-2.02220122 -0.30620401  0.82797464]
  [ 0.23009474  0.76201118 -0.22232814]
  [-0.20075807  0.18656139  0.41005165]]

 [[ 0.19829972  0.11900865 -0.67066229]
  [ 0.37756379  0.12182127  1.12948391]
  [ 1.19891788  0.18515642 -0.37528495]
  [-0.63873041  0.42349435  0.07734007]]]


In [30]:
print(b)

[[[-0.34385368]]]


In [32]:
n1 =np.random.randn(2,2)
print(n1)

[[ 1.2245077   0.40349164]
 [ 0.59357852 -1.09491185]]


In [33]:
n2 =np.random.randn(2,2)
print(n2)

[[ 0.16938243  0.74055645]
 [-0.9537006  -0.26621851]]


In [34]:
np.dot(n1,n2)

array([[-0.17740013,  0.79940014],
       [ 1.14475986,  0.7310642 ]])

In [36]:
n1.shape[0]

2

In [40]:
for r in np.rollaxis(n1, 0):
    print(r)

[1.2245077  0.40349164]
[ 0.59357852 -1.09491185]


In [41]:
n1[0]

array([1.2245077 , 0.40349164])

In [42]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.sum(n1)

1.1266660240923239